name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up Maven settings
        run: echo "${{ secrets.MAVEN_SETTINGS }}" > ~/.m2/settings.xml

      - name: Build and deploy
        run: mvn deploy -s ~/.m2/settings.xml
        env:
          GH_ACTOR: ${{ secrets.GH_ACTOR }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
